version: "3.2"
services:
    redis:
        image: redis:6.2.6
    lab:
        image: lab
        build: ./lab
        depends_on:
            - redis
        ports:
          - "8000:8000"
        volumes:
            - ./data:/home/data
